<?php
namespace Incodiy\Codiy\Database\Seeders\Includes;

use Illuminate\Support\Facades\DB;
/**
 * Created on Dec 12, 2022
 * 
 * Time Created : 1:58:55 PM
 *
 * @filesource	Languages.php
 *
 * @author     wisnuwidi@gmail.com - 2022
 * @copyright  wisnuwidi
 * @email      wisnuwidi@gmail.com
 */
trait Languages {
	
	private function insertLanguages() {
		// LANGUAGE TABLE
		DB::table('base_language')->delete();
		DB::table('base_language')->insert(['abbr' => 'aa_DJ', 'lang' => 'aa', 'language' => 'Afar/Djibouti', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ab_GE', 'lang' => 'ab', 'language' => 'Abkhazian/Georgia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ace_ID', 'lang' => 'ace', 'language' => 'Achinese/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ady_RU', 'lang' => 'ady', 'language' => 'Adyghe/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'af_ZA', 'lang' => 'af', 'language' => 'Afrikaans/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ak_GH', 'lang' => 'ak', 'language' => 'Akan/Ghana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'am_ET', 'lang' => 'am', 'language' => 'Amharic/Ethiopia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_AE', 'lang' => 'ar', 'language' => 'Arabic/United Arab Emirates', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_BH', 'lang' => 'ar', 'language' => 'Arabic/Bahrain', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_DJ', 'lang' => 'ar', 'language' => 'Arabic/Djibouti', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_DZ', 'lang' => 'ar', 'language' => 'Arabic/Algeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_EG', 'lang' => 'ar', 'language' => 'Arabic/Egypt', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_EH', 'lang' => 'ar', 'language' => 'Arabic/Western Sahara', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_ER', 'lang' => 'ar', 'language' => 'Arabic/Eritrea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_IL', 'lang' => 'ar', 'language' => 'Arabic/Israel', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_IQ', 'lang' => 'ar', 'language' => 'Arabic/Iraq', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_JO', 'lang' => 'ar', 'language' => 'Arabic/Jordan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_KM', 'lang' => 'ar', 'language' => 'Arabic/Comoros', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_KW', 'lang' => 'ar', 'language' => 'Arabic/Kuwait', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_LB', 'lang' => 'ar', 'language' => 'Arabic/Lebanon', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_LY', 'lang' => 'ar', 'language' => 'Arabic/Libya', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_MA', 'lang' => 'ar', 'language' => 'Arabic/Morocco', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_MR', 'lang' => 'ar', 'language' => 'Arabic/Mauritania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_OM', 'lang' => 'ar', 'language' => 'Arabic/Oman', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_PS', 'lang' => 'ar', 'language' => 'Arabic/Palestinian Territory', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_QA', 'lang' => 'ar', 'language' => 'Arabic/Qatar', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_SA', 'lang' => 'ar', 'language' => 'Arabic/Saudi Arabia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_SD', 'lang' => 'ar', 'language' => 'Arabic/Sudan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_SY', 'lang' => 'ar', 'language' => 'Arabic/Syria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_TD', 'lang' => 'ar', 'language' => 'Arabic/Chad', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_TN', 'lang' => 'ar', 'language' => 'Arabic/Tunisia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ar_YE', 'lang' => 'ar', 'language' => 'Arabic/Yemen', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ast_ES', 'lang' => 'ast', 'language' => 'Asturian/Spain', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'as_IN', 'lang' => 'as', 'language' => 'Assamese/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'av_RU', 'lang' => 'av', 'language' => 'Avaric/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'awa_IN', 'lang' => 'awa', 'language' => 'Awadhi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ay_BO', 'lang' => 'ay', 'language' => 'Aymara/Bolivia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'az_AZ', 'lang' => 'az', 'language' => 'Azerbaijani/Azerbaijan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bal_PK', 'lang' => 'bal', 'language' => 'Baluchi/Pakistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ban_ID', 'lang' => 'ban', 'language' => 'Balinese/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ba_RU', 'lang' => 'ba', 'language' => 'Bashkir/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bem_ZM', 'lang' => 'bem', 'language' => 'Bemba/Zambia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'be_BY', 'lang' => 'be', 'language' => 'Belarusian/Belarus', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bg_BG', 'lang' => 'bg', 'language' => 'Bulgarian/Bulgaria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bho_IN', 'lang' => 'bho', 'language' => 'Bhojpuri/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bho_MU', 'lang' => 'bho', 'language' => 'Bhojpuri/Mauritius', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bho_NP', 'lang' => 'bho', 'language' => 'Bhojpuri/Nepal', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bin_NG', 'lang' => 'bin', 'language' => 'Bini/Nigeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bi_VU', 'lang' => 'bi', 'language' => 'Bislama/Vanuatu', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bm_ML', 'lang' => 'bm', 'language' => 'Bambara/Mali', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bn_BD', 'lang' => 'bn', 'language' => 'Bengali/Bangladesh', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bn_IN', 'lang' => 'bn', 'language' => 'Bengali/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bo_CN', 'lang' => 'bo', 'language' => 'Tibetan/China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bs_BA', 'lang' => 'bs', 'language' => 'Bosnian/Bosnia and Herzegovina', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'bug_ID', 'lang' => 'bug', 'language' => 'Buginese/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ca_AD', 'lang' => 'ca', 'language' => 'Catalan/Andorra', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ceb_PH', 'lang' => 'ceb', 'language' => 'Cebuano/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ce_RU', 'lang' => 'ce', 'language' => 'Chechen/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'chk_FM', 'lang' => 'chk', 'language' => 'Chuukese/Micronesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ch_GU', 'lang' => 'ch', 'language' => 'Chamorro/Guam', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'cms_IN', 'lang' => 'cms', 'language' => 'Dogri/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'cs_CZ', 'lang' => 'cs', 'language' => 'Czech/Czech Republic', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'cv_RU', 'lang' => 'cv', 'language' => 'Chuvash/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'cy_GB', 'lang' => 'cy', 'language' => 'Welsh/United Kingdom', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'da_DK', 'lang' => 'da', 'language' => 'Danish/Denmark', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'da_GL', 'lang' => 'da', 'language' => 'Danish/Greenland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'de_AT', 'lang' => 'de', 'language' => 'German/Austria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'de_BE', 'lang' => 'de', 'language' => 'German/Belgium', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'de_CH', 'lang' => 'de', 'language' => 'German/Switzerland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'de_DE', 'lang' => 'de', 'language' => 'German/Germany', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'de_LI', 'lang' => 'de', 'language' => 'German/Liechtenstein', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'de_LU', 'lang' => 'de', 'language' => 'German/Luxembourg', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'dv_MV', 'lang' => 'dv', 'language' => 'Divehi/Maldives', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'dyu_BF', 'lang' => 'dyu', 'language' => 'Dyula/Burkina Faso', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'dz_BT', 'lang' => 'dz', 'language' => 'Dzongkha/Bhutan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ee_GH', 'lang' => 'ee', 'language' => 'Ewe/Ghana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'efi_NG', 'lang' => 'efi', 'language' => 'Efik/Nigeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'el_CY', 'lang' => 'el', 'language' => 'Greek/Cyprus', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'el_GR', 'lang' => 'el', 'language' => 'Greek/Greece', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_AG', 'lang' => 'en', 'language' => 'English/Antigua and Barbuda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_AI', 'lang' => 'en', 'language' => 'English/Anguilla', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_AS', 'lang' => 'en', 'language' => 'English/American Samoa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_AU', 'lang' => 'en', 'language' => 'English/Australia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_BB', 'lang' => 'en', 'language' => 'English/Barbados', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_BM', 'lang' => 'en', 'language' => 'English/Bermuda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_BS', 'lang' => 'en', 'language' => 'English/Bahamas', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_BW', 'lang' => 'en', 'language' => 'English/Botswana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_BZ', 'lang' => 'en', 'language' => 'English/Belize', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_CA', 'lang' => 'en', 'language' => 'English/Canada', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_CC', 'lang' => 'en', 'language' => 'English/Cocos Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_CK', 'lang' => 'en', 'language' => 'English/Cook Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_CM', 'lang' => 'en', 'language' => 'English/Cameroon', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_CX', 'lang' => 'en', 'language' => 'English/Christmas Island', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_DM', 'lang' => 'en', 'language' => 'English/Dominica', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_FJ', 'lang' => 'en', 'language' => 'English/Fiji', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_FK', 'lang' => 'en', 'language' => 'English/Falkland Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_FM', 'lang' => 'en', 'language' => 'English/Micronesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GB', 'lang' => 'en', 'language' => 'English/United Kingdom', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GD', 'lang' => 'en', 'language' => 'English/Grenada', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GG', 'lang' => 'en', 'language' => 'English/Guernsey', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GH', 'lang' => 'en', 'language' => 'English/Ghana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GI', 'lang' => 'en', 'language' => 'English/Gibraltar', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GM', 'lang' => 'en', 'language' => 'English/Gambia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GU', 'lang' => 'en', 'language' => 'English/Guam', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_GY', 'lang' => 'en', 'language' => 'English/Guyana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_HK', 'lang' => 'en', 'language' => 'English/Hong Kong SAR China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_HN', 'lang' => 'en', 'language' => 'English/Honduras', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_IE', 'lang' => 'en', 'language' => 'English/Ireland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_IM', 'lang' => 'en', 'language' => 'English/Isle of Man', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_JE', 'lang' => 'en', 'language' => 'English/Jersey', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_JM', 'lang' => 'en', 'language' => 'English/Jamaica', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_KE', 'lang' => 'en', 'language' => 'English/Kenya', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_KI', 'lang' => 'en', 'language' => 'English/Kiribati', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_KN', 'lang' => 'en', 'language' => 'English/Saint Kitts and Nevis', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_KY', 'lang' => 'en', 'language' => 'English/Cayman Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_LC', 'lang' => 'en', 'language' => 'English/Saint Lucia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_LR', 'lang' => 'en', 'language' => 'English/Liberia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_LS', 'lang' => 'en', 'language' => 'English/Lesotho', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_MH', 'lang' => 'en', 'language' => 'English/Marshall Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_MP', 'lang' => 'en', 'language' => 'English/Northern Mariana Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_MS', 'lang' => 'en', 'language' => 'English/Montserrat', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_MT', 'lang' => 'en', 'language' => 'English/Malta', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_MU', 'lang' => 'en', 'language' => 'English/Mauritius', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_MW', 'lang' => 'en', 'language' => 'English/Malawi', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_NA', 'lang' => 'en', 'language' => 'English/Namibia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_NF', 'lang' => 'en', 'language' => 'English/Norfolk Island', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_NG', 'lang' => 'en', 'language' => 'English/Nigeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_NR', 'lang' => 'en', 'language' => 'English/Nauru', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_NU', 'lang' => 'en', 'language' => 'English/Niue', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_NZ', 'lang' => 'en', 'language' => 'English/New Zealand', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_PG', 'lang' => 'en', 'language' => 'English/Papua New Guinea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_PH', 'lang' => 'en', 'language' => 'English/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_PK', 'lang' => 'en', 'language' => 'English/Pakistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_PN', 'lang' => 'en', 'language' => 'English/Pitcairn', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_PR', 'lang' => 'en', 'language' => 'English/Puerto Rico', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_RW', 'lang' => 'en', 'language' => 'English/Rwanda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_SB', 'lang' => 'en', 'language' => 'English/Solomon Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_SC', 'lang' => 'en', 'language' => 'English/Seychelles', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_SG', 'lang' => 'en', 'language' => 'English/Singapore', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_SH', 'lang' => 'en', 'language' => 'English/Saint Helena', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_SL', 'lang' => 'en', 'language' => 'English/Sierra Leone', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_SZ', 'lang' => 'en', 'language' => 'English/Swaziland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_TC', 'lang' => 'en', 'language' => 'English/Turks and Caicos Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_TK', 'lang' => 'en', 'language' => 'English/Tokelau', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_TO', 'lang' => 'en', 'language' => 'English/Tonga', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_TT', 'lang' => 'en', 'language' => 'English/Trinidad and Tobago', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_TV', 'lang' => 'en', 'language' => 'English/Tuvalu', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_TZ', 'lang' => 'en', 'language' => 'English/Tanzania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_UG', 'lang' => 'en', 'language' => 'English/Uganda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_UM', 'lang' => 'en', 'language' => 'English/United States Minor Outlying Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_US', 'lang' => 'en', 'language' => 'English/United States', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_VC', 'lang' => 'en', 'language' => 'English/Saint Vincent and the Grenadines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_VG', 'lang' => 'en', 'language' => 'English/British Virgin Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_VI', 'lang' => 'en', 'language' => 'English/U.S. Virgin Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_VU', 'lang' => 'en', 'language' => 'English/Vanuatu', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_WS', 'lang' => 'en', 'language' => 'English/Samoa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_ZA', 'lang' => 'en', 'language' => 'English/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_ZM', 'lang' => 'en', 'language' => 'English/Zambia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'en_ZW', 'lang' => 'en', 'language' => 'English/Zimbabwe', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_AR', 'lang' => 'es', 'language' => 'Spanish/Argentina', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_BO', 'lang' => 'es', 'language' => 'Spanish/Bolivia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_CL', 'lang' => 'es', 'language' => 'Spanish/Chile', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_CO', 'lang' => 'es', 'language' => 'Spanish/Colombia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_CR', 'lang' => 'es', 'language' => 'Spanish/Costa Rica', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_CU', 'lang' => 'es', 'language' => 'Spanish/Cuba', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_DO', 'lang' => 'es', 'language' => 'Spanish/Dominican Republic', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_EC', 'lang' => 'es', 'language' => 'Spanish/Ecuador', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_ES', 'lang' => 'es', 'language' => 'Spanish/Spain', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_GQ', 'lang' => 'es', 'language' => 'Spanish/Equatorial Guinea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_GT', 'lang' => 'es', 'language' => 'Spanish/Guatemala', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_HN', 'lang' => 'es', 'language' => 'Spanish/Honduras', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_MX', 'lang' => 'es', 'language' => 'Spanish/Mexico', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_NI', 'lang' => 'es', 'language' => 'Spanish/Nicaragua', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_PA', 'lang' => 'es', 'language' => 'Spanish/Panama', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_PE', 'lang' => 'es', 'language' => 'Spanish/Peru', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_PH', 'lang' => 'es', 'language' => 'Spanish/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_PR', 'lang' => 'es', 'language' => 'Spanish/Puerto Rico', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_PY', 'lang' => 'es', 'language' => 'Spanish/Paraguay', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_SV', 'lang' => 'es', 'language' => 'Spanish/El Salvador', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_UY', 'lang' => 'es', 'language' => 'Spanish/Uruguay', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'es_VE', 'lang' => 'es', 'language' => 'Spanish/Venezuela', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'et_EE', 'lang' => 'et', 'language' => 'Estonian/Estonia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'eu_ES', 'lang' => 'eu', 'language' => 'Basque/Spain', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fan_GQ', 'lang' => 'fan', 'language' => 'Fang/Equatorial Guinea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fa_AF', 'lang' => 'fa', 'language' => 'Persian/Afghanistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fa_IR', 'lang' => 'fa', 'language' => 'Persian/Iran', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fil_PH', 'lang' => 'fil', 'language' => 'Filipino/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fi_FI', 'lang' => 'fi', 'language' => 'Finnish/Finland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fj_FJ', 'lang' => 'fj', 'language' => 'Fijian/Fiji', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fon_BJ', 'lang' => 'fon', 'language' => 'Fon/Benin', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fo_FO', 'lang' => 'fo', 'language' => 'Faroese/Faroe Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_BE', 'lang' => 'fr', 'language' => 'French/Belgium', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_BF', 'lang' => 'fr', 'language' => 'French/Burkina Faso', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_BI', 'lang' => 'fr', 'language' => 'French/Burundi', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_BJ', 'lang' => 'fr', 'language' => 'French/Benin', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_BL', 'lang' => 'fr', 'language' => 'French/Saint Barthélemy', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_CA', 'lang' => 'fr', 'language' => 'French/Canada', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_CD', 'lang' => 'fr', 'language' => 'French/Congo - Kinshasa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_CF', 'lang' => 'fr', 'language' => 'French/Central African Republic', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_CG', 'lang' => 'fr', 'language' => 'French/Congo - Brazzaville', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_CH', 'lang' => 'fr', 'language' => 'French/Switzerland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_CI', 'lang' => 'fr', 'language' => 'French/Ivory Coast', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_CM', 'lang' => 'fr', 'language' => 'French/Cameroon', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_DJ', 'lang' => 'fr', 'language' => 'French/Djibouti', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_DZ', 'lang' => 'fr', 'language' => 'French/Algeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_FR', 'lang' => 'fr', 'language' => 'French/France', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_GA', 'lang' => 'fr', 'language' => 'French/Gabon', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_GF', 'lang' => 'fr', 'language' => 'French/French Guiana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_GN', 'lang' => 'fr', 'language' => 'French/Guinea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_GP', 'lang' => 'fr', 'language' => 'French/Guadeloupe', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_GQ', 'lang' => 'fr', 'language' => 'French/Equatorial Guinea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_HT', 'lang' => 'fr', 'language' => 'French/Haiti', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_KM', 'lang' => 'fr', 'language' => 'French/Comoros', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_LU', 'lang' => 'fr', 'language' => 'French/Luxembourg', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_MA', 'lang' => 'fr', 'language' => 'French/Morocco', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_MC', 'lang' => 'fr', 'language' => 'French/Monaco', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_MF', 'lang' => 'fr', 'language' => 'French/Saint Martin', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_MG', 'lang' => 'fr', 'language' => 'French/Madagascar', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_ML', 'lang' => 'fr', 'language' => 'French/Mali', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_MQ', 'lang' => 'fr', 'language' => 'French/Martinique', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_MU', 'lang' => 'fr', 'language' => 'French/Mauritius', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_NC', 'lang' => 'fr', 'language' => 'French/New Caledonia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_NE', 'lang' => 'fr', 'language' => 'French/Niger', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_PF', 'lang' => 'fr', 'language' => 'French/French Polynesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_PM', 'lang' => 'fr', 'language' => 'French/Saint Pierre and Miquelon', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_RE', 'lang' => 'fr', 'language' => 'French/Reunion', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_RW', 'lang' => 'fr', 'language' => 'French/Rwanda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_SC', 'lang' => 'fr', 'language' => 'French/Seychelles', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_SN', 'lang' => 'fr', 'language' => 'French/Senegal', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_SY', 'lang' => 'fr', 'language' => 'French/Syria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_TD', 'lang' => 'fr', 'language' => 'French/Chad', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_TG', 'lang' => 'fr', 'language' => 'French/Togo', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_TN', 'lang' => 'fr', 'language' => 'French/Tunisia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_VU', 'lang' => 'fr', 'language' => 'French/Vanuatu', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_WF', 'lang' => 'fr', 'language' => 'French/Wallis and Futuna', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fr_YT', 'lang' => 'fr', 'language' => 'French/Mayotte', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'fy_NL', 'lang' => 'fy', 'language' => 'Western Frisian/Netherlands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gaa_GH', 'lang' => 'gaa', 'language' => 'Ga/Ghana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ga_IE', 'lang' => 'ga', 'language' => 'Irish/Ireland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gd_GB', 'lang' => 'gd', 'language' => 'Scottish Gaelic/United Kingdom', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gil_KI', 'lang' => 'gil', 'language' => 'Gilbertese/Kiribati', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gl_ES', 'lang' => 'gl', 'language' => 'Galician/Spain', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gn_PY', 'lang' => 'gn', 'language' => 'Guarani/Paraguay', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gon_IN', 'lang' => 'gon', 'language' => 'Gondi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gsw_CH', 'lang' => 'gsw', 'language' => 'Swiss German/Switzerland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gsw_LI', 'lang' => 'gsw', 'language' => 'Swiss German/Liechtenstein', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'gu_IN', 'lang' => 'gu', 'language' => 'Gujarati/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'haw_US', 'lang' => 'haw', 'language' => 'Hawaiian/United States', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ha_NG', 'lang' => 'ha', 'language' => 'Hausa/Nigeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'he_IL', 'lang' => 'he', 'language' => 'Hebrew/Israel', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'hil_PH', 'lang' => 'hil', 'language' => 'Hiligaynon/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'hi_IN', 'lang' => 'hi', 'language' => 'Hindi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ho_PG', 'lang' => 'ho', 'language' => 'Hiri Motu/Papua New Guinea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'hr_BA', 'lang' => 'hr', 'language' => 'Croatian/Bosnia and Herzegovina', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'hr_HR', 'lang' => 'hr', 'language' => 'Croatian/Croatia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ht_HT', 'lang' => 'ht', 'language' => 'Haitian/Haiti', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'hu_HU', 'lang' => 'hu', 'language' => 'Hungarian/Hungary', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'hy_AM', 'lang' => 'hy', 'language' => 'Armenian/Armenia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'id_ID', 'lang' => 'id', 'language' => 'Indonesian/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ig_NG', 'lang' => 'ig', 'language' => 'Igbo/Nigeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ii_CN', 'lang' => 'ii', 'language' => 'Sichuan Yi/China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ilo_PH', 'lang' => 'ilo', 'language' => 'Iloko/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'inh_RU', 'lang' => 'inh', 'language' => 'Ingush/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'is_IS', 'lang' => 'is', 'language' => 'Icelandic/Iceland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'it_CH', 'lang' => 'it', 'language' => 'Italian/Switzerland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'it_IT', 'lang' => 'it', 'language' => 'Italian/Italy', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'it_SM', 'lang' => 'it', 'language' => 'Italian/San Marino', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'iu_CA', 'lang' => 'iu', 'language' => 'Inuktitut/Canada', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'iu_GL', 'lang' => 'iu', 'language' => 'Inuktitut/Greenland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ja_JP', 'lang' => 'ja', 'language' => 'Japanese/Japan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'jv_ID', 'lang' => 'jv', 'language' => 'Javanese/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kab_DZ', 'lang' => 'kab', 'language' => 'Kabyle/Algeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kam_KE', 'lang' => 'kam', 'language' => 'Kamba/Kenya', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ka_GE', 'lang' => 'ka', 'language' => 'Georgian/Georgia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kbd_RU', 'lang' => 'kbd', 'language' => 'Kabardian/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kg_CD', 'lang' => 'kg', 'language' => 'Kongo/Congo - Kinshasa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kha_IN', 'lang' => 'kha', 'language' => 'Khasi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ki_KE', 'lang' => 'ki', 'language' => 'Kikuyu/Kenya', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kj_NA', 'lang' => 'kj', 'language' => 'Kuanyama/Namibia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kk_KZ', 'lang' => 'kk', 'language' => 'Kazakh/Kazakhstan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kl_GL', 'lang' => 'kl', 'language' => 'Kalaallisut/Greenland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kmb_AO', 'lang' => 'kmb', 'language' => 'Kimbundu/Angola', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'km_KH', 'lang' => 'km', 'language' => 'Khmer/Cambodia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kn_IN', 'lang' => 'kn', 'language' => 'Kannada/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kok_IN', 'lang' => 'kok', 'language' => 'Konkani/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kos_FM', 'lang' => 'kos', 'language' => 'Kosraean/Micronesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ko_KP', 'lang' => 'ko', 'language' => 'Korean/North Korea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ko_KR', 'lang' => 'ko', 'language' => 'Korean/South Korea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'krc_RU', 'lang' => 'krc', 'language' => 'Karachay-Balkar/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kru_IN', 'lang' => 'kru', 'language' => 'Kurukh/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ks_IN', 'lang' => 'ks', 'language' => 'Kashmiri/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'kum_RU', 'lang' => 'kum', 'language' => 'Kumyk/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ku_IQ', 'lang' => 'ku', 'language' => 'Kurdish/Iraq', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ku_IR', 'lang' => 'ku', 'language' => 'Kurdish/Iran', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ku_SY', 'lang' => 'ku', 'language' => 'Kurdish/Syria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ku_TR', 'lang' => 'ku', 'language' => 'Kurdish/Turkey', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ky_KG', 'lang' => 'ky', 'language' => 'Kirghiz/Kyrgyzstan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lah_PK', 'lang' => 'lah', 'language' => 'Lahnda/Pakistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'la_VA', 'lang' => 'la', 'language' => 'Latin/Vatican', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lb_LU', 'lang' => 'lb', 'language' => 'Luxembourgish/Luxembourg', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lez_RU', 'lang' => 'lez', 'language' => 'Lezghian/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lg_UG', 'lang' => 'lg', 'language' => 'Ganda/Uganda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ln_CD', 'lang' => 'ln', 'language' => 'Lingala/Congo - Kinshasa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ln_CG', 'lang' => 'ln', 'language' => 'Lingala/Congo - Brazzaville', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lo_LA', 'lang' => 'lo', 'language' => 'Lao/Laos', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lt_LT', 'lang' => 'lt', 'language' => 'Lithuanian/Lithuania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lua_CD', 'lang' => 'lua', 'language' => 'Luba-Lulua/Congo - Kinshasa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'luo_KE', 'lang' => 'luo', 'language' => 'Luo/Kenya', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lu_CD', 'lang' => 'lu', 'language' => 'Luba-Katanga/Congo - Kinshasa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'lv_LV', 'lang' => 'lv', 'language' => 'Latvian/Latvia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mad_ID', 'lang' => 'mad', 'language' => 'Madurese/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mag_IN', 'lang' => 'mag', 'language' => 'Magahi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mai_IN', 'lang' => 'mai', 'language' => 'Maithili/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mai_NP', 'lang' => 'mai', 'language' => 'Maithili/Nepal', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mak_ID', 'lang' => 'mak', 'language' => 'Makasar/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mdf_RU', 'lang' => 'mdf', 'language' => 'Moksha/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'men_SL', 'lang' => 'men', 'language' => 'Mende/Sierra Leone', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mg_MG', 'lang' => 'mg', 'language' => 'Malagasy/Madagascar', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mh_MH', 'lang' => 'mh', 'language' => 'Marshallese/Marshall Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'min_ID', 'lang' => 'min', 'language' => 'Minangkabau/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mi_NZ', 'lang' => 'mi', 'language' => 'Maori/New Zealand', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mk_MK', 'lang' => 'mk', 'language' => 'Macedonian/Macedonia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ml_IN', 'lang' => 'ml', 'language' => 'Malayalam/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mni_IN', 'lang' => 'mni', 'language' => 'Manipuri/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mn_MN', 'lang' => 'mn', 'language' => 'Mongolian/Mongolia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mos_BF', 'lang' => 'mos', 'language' => 'Mossi/Burkina Faso', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mr_IN', 'lang' => 'mr', 'language' => 'Marathi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ms_BN', 'lang' => 'ms', 'language' => 'Malay/Brunei', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ms_MY', 'lang' => 'ms', 'language' => 'Malay/Malaysia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ms_SG', 'lang' => 'ms', 'language' => 'Malay/Singapore', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'mt_MT', 'lang' => 'mt', 'language' => 'Maltese/Malta', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'myv_RU', 'lang' => 'myv', 'language' => 'Erzya/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'my_MM', 'lang' => 'my', 'language' => 'Burmese/Myanmar', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nap_IT', 'lang' => 'nap', 'language' => 'Neapolitan/Italy', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'na_NR', 'lang' => 'na', 'language' => 'Nauru/Nauru', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nb_NO', 'lang' => 'nb', 'language' => 'Norwegian Bokmål/Norway', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nb_SJ', 'lang' => 'nb', 'language' => 'Norwegian Bokmål/Svalbard and Jan Mayen', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nd_ZW', 'lang' => 'nd', 'language' => 'North Ndebele/Zimbabwe', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ne_NP', 'lang' => 'ne', 'language' => 'Nepali/Nepal', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ng_NA', 'lang' => 'ng', 'language' => 'Ndonga/Namibia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'niu_NU', 'lang' => 'niu', 'language' => 'Niuean/Niue', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nl_AN', 'lang' => 'nl', 'language' => 'Dutch/Netherlands Antilles', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nl_AW', 'lang' => 'nl', 'language' => 'Dutch/Aruba', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nl_BE', 'lang' => 'nl', 'language' => 'Dutch/Belgium', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nl_NL', 'lang' => 'nl', 'language' => 'Dutch/Netherlands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nl_SR', 'lang' => 'nl', 'language' => 'Dutch/Suriname', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nn_NO', 'lang' => 'nn', 'language' => 'Norwegian Nynorsk/Norway', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nso_ZA', 'lang' => 'nso', 'language' => 'Northern Sotho/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nym_TZ', 'lang' => 'nym', 'language' => 'Nyamwezi/Tanzania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'nyn_UG', 'lang' => 'nyn', 'language' => 'Nyankole/Uganda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ny_MW', 'lang' => 'ny', 'language' => 'Nyanja/Malawi', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'oc_FR', 'lang' => 'oc', 'language' => 'Occitan/France', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'om_ET', 'lang' => 'om', 'language' => 'Oromo/Ethiopia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'or_IN', 'lang' => 'or', 'language' => 'Oriya/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'os_GE', 'lang' => 'os', 'language' => 'Ossetic/Georgia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pag_PH', 'lang' => 'pag', 'language' => 'Pangasinan/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pam_PH', 'lang' => 'pam', 'language' => 'Pampanga/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pap_AN', 'lang' => 'pap', 'language' => 'Papiamento/Netherlands Antilles', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pau_PW', 'lang' => 'pau', 'language' => 'Palauan/Palau', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pa_IN', 'lang' => 'pa', 'language' => 'Punjabi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pl_PL', 'lang' => 'pl', 'language' => 'Polish/Poland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pon_FM', 'lang' => 'pon', 'language' => 'Pohnpeian/Micronesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ps_AF', 'lang' => 'ps', 'language' => 'Pashto/Afghanistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_AO', 'lang' => 'pt', 'language' => 'Portuguese/Angola', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_BR', 'lang' => 'pt', 'language' => 'Portuguese/Brazil', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_CV', 'lang' => 'pt', 'language' => 'Portuguese/Cape Verde', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_GW', 'lang' => 'pt', 'language' => 'Portuguese/Guinea-Bissau', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_MZ', 'lang' => 'pt', 'language' => 'Portuguese/Mozambique', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_PT', 'lang' => 'pt', 'language' => 'Portuguese/Portugal', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_ST', 'lang' => 'pt', 'language' => 'Portuguese/Sao Tome and Principe', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'pt_TL', 'lang' => 'pt', 'language' => 'Portuguese/East Timor', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'qu_BO', 'lang' => 'qu', 'language' => 'Quechua/Bolivia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'qu_PE', 'lang' => 'qu', 'language' => 'Quechua/Peru', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'rm_CH', 'lang' => 'rm', 'language' => 'Rhaeto-Romance/Switzerland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'rn_BI', 'lang' => 'rn', 'language' => 'Rundi/Burundi', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ro_MD', 'lang' => 'ro', 'language' => 'Romanian/Moldova', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ro_RO', 'lang' => 'ro', 'language' => 'Romanian/Romania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ru_BY', 'lang' => 'ru', 'language' => 'Russian/Belarus', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ru_KG', 'lang' => 'ru', 'language' => 'Russian/Kyrgyzstan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ru_KZ', 'lang' => 'ru', 'language' => 'Russian/Kazakhstan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ru_RU', 'lang' => 'ru', 'language' => 'Russian/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'rw_RW', 'lang' => 'rw', 'language' => 'Kinyarwanda/Rwanda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sah_RU', 'lang' => 'sah', 'language' => 'Yakut/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sas_ID', 'lang' => 'sas', 'language' => 'Sasak/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sat_IN', 'lang' => 'sat', 'language' => 'Santali/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sa_IN', 'lang' => 'sa', 'language' => 'Sanskrit/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'scn_IT', 'lang' => 'scn', 'language' => 'Sicilian/Italy', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sco_GB', 'lang' => 'sco', 'language' => 'Scots/United Kingdom', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sd_IN', 'lang' => 'sd', 'language' => 'Sindhi/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'se_NO', 'lang' => 'se', 'language' => 'Northern Sami/Norway', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sg_CF', 'lang' => 'sg', 'language' => 'Sango/Central African Republic', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'shn_MM', 'lang' => 'shn', 'language' => 'Shan/Myanmar', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sid_ET', 'lang' => 'sid', 'language' => 'Sidamo/Ethiopia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'si_LK', 'lang' => 'si', 'language' => 'Sinhalese/Sri Lanka', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sk_SK', 'lang' => 'sk', 'language' => 'Slovak/Slovakia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sl_SI', 'lang' => 'sl', 'language' => 'Slovenian/Slovenia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sm_AS', 'lang' => 'sm', 'language' => 'Samoan/American Samoa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sm_WS', 'lang' => 'sm', 'language' => 'Samoan/Samoa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sn_ZW', 'lang' => 'sn', 'language' => 'Shona/Zimbabwe', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'so_SO', 'lang' => 'so', 'language' => 'Somali/Somalia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sq_AL', 'lang' => 'sq', 'language' => 'Albanian/Albania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'srn_SR', 'lang' => 'srn', 'language' => 'Sranan Tongo/Suriname', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'srr_SN', 'lang' => 'srr', 'language' => 'Serer/Senegal', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sr_BA', 'lang' => 'sr', 'language' => 'Serbian/Bosnia and Herzegovina', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sr_ME', 'lang' => 'sr', 'language' => 'Serbian/Montenegro', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sr_RS', 'lang' => 'sr', 'language' => 'Serbian/Serbia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ss_SZ', 'lang' => 'ss', 'language' => 'Swati/Swaziland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'st_LS', 'lang' => 'st', 'language' => 'Southern Sotho/Lesotho', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'st_ZA', 'lang' => 'st', 'language' => 'Southern Sotho/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'suk_TZ', 'lang' => 'suk', 'language' => 'Sukuma/Tanzania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'su_ID', 'lang' => 'su', 'language' => 'Sundanese/Indonesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sv_AX', 'lang' => 'sv', 'language' => 'Swedish/Aland Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sv_FI', 'lang' => 'sv', 'language' => 'Swedish/Finland', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sv_SE', 'lang' => 'sv', 'language' => 'Swedish/Sweden', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sw_KE', 'lang' => 'sw', 'language' => 'Swahili/Kenya', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sw_TZ', 'lang' => 'sw', 'language' => 'Swahili/Tanzania', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'sw_UG', 'lang' => 'sw', 'language' => 'Swahili/Uganda', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ta_IN', 'lang' => 'ta', 'language' => 'Tamil/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ta_LK', 'lang' => 'ta', 'language' => 'Tamil/Sri Lanka', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ta_SG', 'lang' => 'ta', 'language' => 'Tamil/Singapore', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tem_SL', 'lang' => 'tem', 'language' => 'Timne/Sierra Leone', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tet_TL', 'lang' => 'tet', 'language' => 'Tetum/East Timor', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'te_IN', 'lang' => 'te', 'language' => 'Telugu/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tg_TJ', 'lang' => 'tg', 'language' => 'Tajik/Tajikistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'th_TH', 'lang' => 'th', 'language' => 'Thai/Thailand', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tiv_NG', 'lang' => 'tiv', 'language' => 'Tiv/Nigeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ti_ER', 'lang' => 'ti', 'language' => 'Tigrinya/Eritrea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tkl_TK', 'lang' => 'tkl', 'language' => 'Tokelau/Tokelau', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tk_TM', 'lang' => 'tk', 'language' => 'Turkmen/Turkmenistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tl_PH', 'lang' => 'tl', 'language' => 'Tagalog/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tl_US', 'lang' => 'tl', 'language' => 'Tagalog/United States', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tn_BW', 'lang' => 'tn', 'language' => 'Tswana/Botswana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tn_ZA', 'lang' => 'tn', 'language' => 'Tswana/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'to_TO', 'lang' => 'to', 'language' => 'Tonga/Tonga', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tpi_PG', 'lang' => 'tpi', 'language' => 'Tok Pisin/Papua New Guinea', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tr_CY', 'lang' => 'tr', 'language' => 'Turkish/Cyprus', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tr_TR', 'lang' => 'tr', 'language' => 'Turkish/Turkey', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ts_ZA', 'lang' => 'ts', 'language' => 'Tsonga/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tt_RU', 'lang' => 'tt', 'language' => 'Tatar/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tvl_TV', 'lang' => 'tvl', 'language' => 'Tuvalu/Tuvalu', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tw_GH', 'lang' => 'tw', 'language' => 'Twi/Ghana', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'tyv_RU', 'lang' => 'tyv', 'language' => 'Tuvinian/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ty_PF', 'lang' => 'ty', 'language' => 'Tahitian/French Polynesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'udm_RU', 'lang' => 'udm', 'language' => 'Udmurt/Russia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ug_CN', 'lang' => 'ug', 'language' => 'Uighur/China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'uk_UA', 'lang' => 'uk', 'language' => 'Ukrainian/Ukraine', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'umb_AO', 'lang' => 'umb', 'language' => 'Umbundu/Angola', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'und_AQ', 'lang' => 'und', 'language' => 'Unknown or Invalid Language/Antarctica', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'und_BV', 'lang' => 'und', 'language' => 'Unknown or Invalid Language/Bouvet Island', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'und_GS', 'lang' => 'und', 'language' => 'Unknown or Invalid Language/South Georgia and the South Sandwich Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'und_HM', 'lang' => 'und', 'language' => 'Unknown or Invalid Language/Heard Island and McDonald Islands', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'und_IO', 'lang' => 'und', 'language' => 'Unknown or Invalid Language/British Indian Ocean Territory', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'und_TF', 'lang' => 'und', 'language' => 'Unknown or Invalid Language/French Southern Territories', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ur_IN', 'lang' => 'ur', 'language' => 'Urdu/India', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'ur_PK', 'lang' => 'ur', 'language' => 'Urdu/Pakistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'uz_UZ', 'lang' => 'uz', 'language' => 'Uzbek/Uzbekistan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 've_ZA', 'lang' => 've', 'language' => 'Venda/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'vi_VN', 'lang' => 'vi', 'language' => 'Vietnamese/Vietnam', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'wal_ET', 'lang' => 'wal', 'language' => 'Walamo/Ethiopia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'war_PH', 'lang' => 'war', 'language' => 'Waray/Philippines', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'wo_SN', 'lang' => 'wo', 'language' => 'Wolof/Senegal', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'xh_ZA', 'lang' => 'xh', 'language' => 'Xhosa/South Africa', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'yap_FM', 'lang' => 'yap', 'language' => 'Yapese/Micronesia', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'yo_NG', 'lang' => 'yo', 'language' => 'Yoruba/Nigeria', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'za_CN', 'lang' => 'za', 'language' => 'Zhuang/China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'zh_CN', 'lang' => 'zh', 'language' => 'Chinese/China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'zh_HK', 'lang' => 'zh', 'language' => 'Chinese/Hong Kong SAR China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'zh_MO', 'lang' => 'zh', 'language' => 'Chinese/Macao SAR China', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'zh_SG', 'lang' => 'zh', 'language' => 'Chinese/Singapore', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'zh_TW', 'lang' => 'zh', 'language' => 'Chinese/Taiwan', 'charset' => 'utf-8']);
		DB::table('base_language')->insert(['abbr' => 'zu_ZA', 'lang' => 'zu', 'language' => 'Zulu/South Africa', 'charset' => 'utf-8']);
	}
}